src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;


/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="date")
     */
    private $Date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */

    private $prix;

    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param mixed $file
     */
    public function setFile($file): void
    {
        $this->file = $file;
    }

    /**
     * @Assert\File(maxSize="700k")
     */
    public $file;
    /**
     * @return mixed;
     */


    /**
     * @ORM\Column(type="integer")
     */
    private $nb_places;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @var int
     * @ORM\Column(name="nb_signal",type="integer")
     */
    private $nb_signal;
    /**
     * @var
     * @ORM\ManyToMany(targetEntity="App\Entity\User")
     * @ORM\JoinTable(name="user_signal",
     *     joinColumns={
     *          @ORM\JoinColumn(name="event_id", referencedColumnName="id")
     *     },
     *     inverseJoinColumns={
     *          @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     *     }
     * )
     */
    private $usersSignal;

    /**
     * @return mixed
     */
    public function getUsersSignal()
    {
        return $this->usersSignal;
    }

    /**
     * @param mixed $usersSignal
     */
    public function setUsersSignal($usersSignal): void
    {
        $this->usersSignal = $usersSignal;
    }


    /**
     * @return mixed
     */
    public function getNbSignal()
    {
        return $this->nb_signal;
    }

    /**
     * @param mixed $nb_signal
     */
    public function setNbSignal($nb_signal): void
    {
        $this->nb_signal = $nb_signal;
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $nom_image;

    /**
     * @return mixed
     */
    public function getNomImage()
    {
        return $this->nom_image;
    }

    /**
     * @param mixed $nom_image
     */
    public function setNomImage($nom_image): void
    {
        $this->nom_image = $nom_image;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->Date_debut;
    }

    public function setDateDebut(\DateTimeInterface $Date_debut): self
    {
        $this->Date_debut = $Date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nb_places;
    }

    public function setNbPlaces(int $nb_places): self
    {
        $this->nb_places = $nb_places;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }




    /**
     * @var
     * @ORM\ManyToMany( targetEntity="App\Entity\User",inversedBy="events")
     * @ORM\JoinTable(name="user_event",
     *     joinColumns={
     *          @ORM\JoinColumn(name="event_id", referencedColumnName="id")
     *     },
     *     inverseJoinColumns={
     *          @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     *     }
     * )
     */
    private $users;


    /**
     * @param mixed $users
     */
    public function setUsers($users)
    {
        $this->users = $users;
    }

    public function __construct()
    {
        $this->users= new ArrayCollection();
        $this->events= new ArrayCollection();

    }
    /**
     * @return ArrayCollection|users[]
     *
     */
    public function getUsers()
    {
        return $this->users;
    }




    public function addUsers( $user)
    {
        if ($this->users->contains($user)) {
            return;
        }
        $this->users->add($user);
        $user->addEvent($this);
    }



    public function removeUsers( $user)
    {
        if (!$this->users->contains($user)) {
            return;
        }

        $this->users->removeElement($user);
        $user->removeevent($this);
    }


    public function __toString()
    {

        return $this->Nom;
    }

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="events")
     */
    private $creator;



    /**
     * @return mixed
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * @param mixed $creator
     */
    public function setCreator($creator)
    {
        $this->creator = $creator;
    }

    /**
     * @return int
     */


    public function getWebPath(){

        return null===$this->nom_image ? null :$this->getUploadDir().'/'.$this->nom_image;
    }
    protected function getUploadRootDir()
    {

        return (dirname(__FILE__). '/../../../assets/' . $this->getUploadDir());
    }
    protected function getUploadDir(){

        return 'images';
    }


    public function uploadProfilePicture(){
        $this->file->move($this->getUploadRootDir(),$this->file->getClientOriginalName());
        $this->nom_image=$this->file->getClientOriginalName();
        $this->file=null;
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\Images;
use App\Entity\Recherche;
use App\Entity\Recu;
use App\Form\EventType;
use App\Form\RechercheeType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use Endroid\QrCode\QrCode;


/**
 * @Route("/event")
 */
class EventController extends AbstractController

{
    /**
     * @Route("/participer{id}", name="event_participer", methods={"GET"})
     */
    public function participerAction($id, \Swift_Mailer $mailer)
    {

        $em = $this->getDoctrine()->getManager();
        $Recu = new Recu();
        $datej = new \DateTime('now');
        $datej2 = $datej->format('Y-m-d');
        $event = $em->getRepository(Event::class)->find($id);
        $datedb = $event->getDateDebut();
        $datedb1 = $datedb->format('Y-m-d');

        //$userid = $this->getUser()->getId();
        $user = $em->getRepository(User::class)->find(3);
        if ($event->getUsers()->contains($user)) {
            $msg = "Vous etes deja inscrit a cet evennement ";
            return $this->render('event/front/participationFailed.html.twig', array('msg' => $msg));

        } else if ($datedb1 < $datej2) {
            $msg = "vous ne pouvez plus participer a cet evennement ";
            return $this->render('event/front/participationFailed.html.twig', array('msg' => $msg));

        } else if ($event->getNbPlaces() <= 0) {
            $msg = "Nous sommes désolé , il n'y a plus de places disponible ";
            return $this->render('event/front/participationFailed.html.twig', array('msg' => $msg));

        } else {
            $users = $event->getUsers();
            $Recu->setUser($user);
            $Recu->setEvent($event);
            $Recu->setPrixrecu($event->getprix());
            $em->persist($Recu);
            $users->add($user);
            $event->setUsers($users);
            $event->setNbPlaces($event->getNbPlaces() - 1);
            $em->persist($event);

           /*$qrCode = new QrCode('Bonjour Monsieur : ' . $user->getNom() . ' , ceci votre ticket vous avez participé à l\'événement : ' . $event->getNom() .
                ' , Date debut : ' .  $datedb1);
            header('Content-Type: image/png');
            $qrCode->writeFile('Evenement/image/qrcode/qrcode.png');*/

            $email = $user->getGmail();
            $id = $user->getId();
            $message = (new \Swift_Message())
                ->setSubject($event->getNom())
                ->setFrom('projet.pidev1@gmail.com')
                ->setTo($email)
                ->setBody(
                    'votre ticket ');
                /*->attach(Swift_Attachment::fromPath('Evenement/image/qrcode/qrcode.png')
                    ->setDisposition('inline'));*/



            $mailer->send($message);

            $em->flush();
            $msg = "Vous avez particper a cet evenemment avec succé !! ";
            return $this->render('event/front/participationSuccess.html.twig', array('msg' => $msg));

        }
    }
    /**
     * @Route("/annuler{id}", name="event_annuler", methods={"GET"})
     */
    public function annulerParticipationAction($id){
        $em = $this->getDoctrine()->getManager();
        $event = $em->getRepository(Event::class)->find($id);
        //$userid = $this->getUser()->getId();
        $user = $em->getRepository(User ::class)->find(1);
        $event->setNbPlaces($event->getNbPlaces() + 1);
        $users =  $event->getUsers();
        $users->removeElement($user);
        $event->setUsers($users);
        $em->flush();
        return $this->redirectToRoute('event_index');


    }

    /**
     *@Route("/Recherche",name="Recherche")
     * Method({"GET", "POST"})
     */

    public function home(Request $request)
    {
        $Recherche= new Recherche();
        $form = $this->createForm(RechercheeType::class,$Recherche);
        $form->handleRequest($request);
        //initialement le tableau des articles est vide,
        //c.a.d on affiche les articles que lorsque l'utilisateur clique sur le bouton rechercher
        $events= [];

        if($form->isSubmitted() && $form->isValid()) {
            //on récupère le nom d'article tapé dans le formulaire
            $val = $Recherche->getNom();
            if ($val!="")
                //si on a fourni un nom d'article on affiche tous les articles ayant ce nom
                $events= $this->getDoctrine()->getRepository(Event::class)->findByNom($val);
            else
                //si si aucun nom n'est fourni on affiche tous les articles
                $events= $this->getDoctrine()->getRepository(Event::class)->findAll();
        }
        return  $this->render('Event/Recherche.html.twig',[ 'form' =>$form->createView(), 'events' => $events]);
    }
    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository): Response
    {
        $u ="gmiza";
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
            'u'=>$u

        ]);
    }
    /**
     * @Route("back/", name="event_indexback", methods={"GET"})
     */
    public function indexback(EventRepository $eventRepository): Response
    {
        $u ="gmiza";
        return $this->render('event/indexback.html.twig', [
            'events' => $eventRepository->findAll(),
            'u'=>$u

        ]);
    }
    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $event->uploadProfilePicture();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}", name="event_show")
     *  Method({"GET", "POST"})
     */
    public function show(Request $request,Event $event): Response
    {
        



        $em = $this->getDoctrine()->getManager();
        $id= $event->getId();
        //$comments = $em->getRepository(Commentaire::class)->findByEvent(2);
        $comments = $em->getRepository(Commentaire::class)->findByevent($event);
        $comment = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $comment);
        $form->handleRequest($request);
        //$userid = $this->getUser()->getId();
        $user = $em->getRepository(User::class)->find(1);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $comment->setEvent($event);
            $comment->setUser($user);
            $em->persist($comment);
            $em->flush();
            $entityManager->persist($comment);
            $entityManager->flush();
        }
            return $this->render('event/show.html.twig', array(

                'event' => $event,
                'comments' => $comments,
                'form' => $form->createView()


            ));
    }


    /**
     * @Route("/back/{id}", name="event_showback")
     *  Method({"GET", "POST"})
     */
    public function showback(Request $request,Event $event): Response
    {




        $em = $this->getDoctrine()->getManager();
        $id= $event->getId();
        //$comments = $em->getRepository(Commentaire::class)->findByEvent(2);
        $comments = $em->getRepository(Commentaire::class)->findByevent($event);
        $comment = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $comment);
        $form->handleRequest($request);
        //$userid = $this->getUser()->getId();
        $user = $em->getRepository(User::class)->find(1);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $comment->setEvent($event);
            $comment->setUser($user);
            $em->persist($comment);
            $em->flush();
            $entityManager->persist($comment);
            $entityManager->flush();
        }
        return $this->render('event/showback.html.twig', array(

            'event' => $event,
            'comments' => $comments,
            'form' => $form->createView()


        ));
    }
    /**
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }

    /**
     * @Route("/back", name="back")
     */

templates/event/Recherche.html.twig
{% extends 'base.html.twig' %}

{% block body2 %}

    {{ form_start(form)}}

    <div class="form-row align-items-end" >
        <div class="col">
            {{ form_row(form.nom) }}
        </div>

        <div class="col">
            <div class="form-group">
                <button type="submit" class="btn btn-success">Rechercher</button>
            </div>
        </div>
    </div>
    {{ form_end(form)}}

    {% if events %}
        <table id="events" class="table table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Description</th>
                <th>Lieu</th>
                <th>Prix</th>
                <th>Nb_places</th>
                <th>Type</th>
                <th>Nb_signal</th>
                <th>Nom_image</th>
                <th>actions</th>
            </tr>


            </thead>
            <tbody>
            {% for event in events %}
                <tr>
                    <td>{{ event.id }}</td>
                    <td>{{ event.Nom }}</td>
                    <td>{{ event.DateDebut ? event.DateDebut|date('Y-m-d') : '' }}</td>
                    <td>{{ event.dateFin ? event.dateFin|date('Y-m-d') : '' }}</td>
                    <td>{{ event.description }}</td>
                    <td>{{ event.lieu }}</td>
                    <td>{{ event.prix }}</td>
                    <td>{{ event.nbPlaces }}</td>
                    <td>{{ event.type }}</td>
                    <td>{{ event.nbSignal }}</td>
                    <td>{{ event.nomImage }}</td>


                    <td>

                        <a href="{{ path('event_show', {'id': event.id}) }}">show</a>
                        <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucun Event</p>
    {% endif %}
{% endblock %}


{% block body3 %}
{% endblock %}

{% block body4 %}
{% endblock %}




{% block body6 %}
{% endblock %}

{% block body7 %}
{% endblock %}

templates/event/Signal.html.twig
{% extends 'base.html.twig' %}
{% block body1 %}
{% endblock %}

{% block body2 %}
{% endblock %}

{% block body3 %}
{% endblock %}

{% block body4 %}
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_signal') }}">back to list</a>

{% endblock %}
{% block body5 %}
{% endblock %}

{% block body6 %}
{% endblock %}

templates/event/_delete_form.html.twig
{% extends 'base.html.twig' %}
{% block body1 %}
{% endblock %}

{% block body2 %}
{% endblock %}

{% block body3 %}
{% endblock %}

{% block body4 %}


<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

{% endblock %}

{% block body5 %}
{% endblock %}

{% block body6 %}
{% endblock %}

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block body1 %}
{% endblock %}

{% block body2 %}
{% endblock %}

{% block body3 %}
{% endblock %}

{% block body4 %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('event_index') }}">back to list</a>



    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

{% block body5 %}
{% endblock %}

{% block body6 %}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}
{% block body1 %}

{% endblock %}


{% block body2 %}
{% endblock %}

{% block body3 %}
{% endblock %}



{% block body4 %}

    <div class="album py-5 bg-light">
        <div class="container">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <div class="row">

                {% for event in events %}

                        <a href="{{ path('event_show', { 'id': event.id }) }}" style="color: black">
                            <div class="col-md-4">
                                <div class="card mb-4 card-shadow ">
                                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ asset('assets/images/') }}{{ event.nom_image }}" data-holder-rendered="true">
                                    <div class="card-body">
                                        <strong> <p class="card-text " style="font-size: 20px">{{ event.Nom}}</p></strong>


                                        <p class="card-text b">{{ event.description}}</p>
                                        <div class="btn-group">
                                        </div>
                                        <div class="card-footer">
                                            <div class="d-flex justify-content-between align-items-center">



                                                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ path('event_participer', { 'id': event.id }) }}">participer</a></button>
                                                <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ path('event_signal', { 'id': event.id }) }}">Signaler</a></button>

                                                {% if  u  in event.users %}
                                                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ path('event_annuler', { 'id': event.id }) }}">annuler</a></button>
                                                {% endif%}

                                            </div>
                                            <br>
                                            {{ event.DateDebut ? event.DateDebut|date('Y-m-d') : '' }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>

                {% endfor %}
            </div>
        </div>
    </div>
    </br>
    </br>
    <center>
        <a href="{{ path('event_new') }}" class="btn btn-primary btn-lg">
            Ajouter un nouvel évennement
        </a>
    </center>
    </div>
{% endblock %}

{% block body5 %}
{% endblock %}
{% block body6 %}
{% endblock %}

templates/event/indexAdmin.html.twig
{% extends 'base.html.twig' %}
{% block body1 %}

{% endblock %}


{% block body2 %}
{% endblock %}

{% block body3 %}
{% endblock %}



{% block body4 %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for event in events %}

                    <a href="{{ path('event_show', { 'id': event.id }) }}" style="color: black">
                        <div class="col-md-4">
                            <div class="card mb-4 card-shadow ">
                                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ asset('assets/images/') }}{{ event.nom_image }}" data-holder-rendered="true">
                                <div class="card-body">
                                    <strong> <p class="card-text " style="font-size: 20px">{{ event.Nom}}</p></strong>


                                    <p class="card-text b">{{ event.description}}</p>
                                    <div class="btn-group">
                                    </div>
                                    <div class="card-footer">
                                        <div class="d-flex justify-content-between align-items-center">

                                            {% for event in events %}

                                            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ path('event_participer', { 'id': event.id }) }}">participer</a></button>
                                            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ path('event_edit', {'id': event.id}) }}">edit</a></button>

                                            {% endfor %}
                                            {% if  u  in event.users %}
                                                <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{{ path('event_annuler', { 'id': event.id }) }}">annuler</a></button>
                                            {% endif %}
                                        </div>
                                        <br>
                                        {{ event.DateDebut ? event.DateDebut|date('Y-m-d') : '' }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>

                {% endfor %}
            </div>
        </div>
    </div>
    </br>
    </br>
    <center>
        <a href="{{ path('event_new') }}" class="btn btn-primary btn-lg">
            Ajouter un nouvel évennement
        </a>
    </center>
    </div>
{% endblock %}

{% block body5 %}
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}
{% block body1 %}
{% endblock %}

{% block body2 %}
{% endblock %}

{% block body3 %}
{% endblock %}

{% block body4 %}
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_index') }}">back to list</a>

{% endblock %}
{% block body5 %}
{% endblock %}

{% block body6 %}
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block body1 %}
{% endblock %}

{% block body2 %}
{% endblock %}

{% block body3 %}
{% endblock %}
{% block body4%}

    <h1>Event</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ event.Nom }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ event.DateDebut ? event.DateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ event.dateFin ? event.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ event.lieu }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ event.prix }}</td>
            </tr>
            <tr>
                <th>Nb_places</th>
                <td>{{ event.nbPlaces }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ event.type }}</td>
            </tr>
            <tr>
                <th>Nb_signal</th>
                <td>{{ event.nbSignal }}</td>
            </tr>
            <tr>

                <!-- Preview Image -->

                <img src="{{ asset('assets/images/') }}{{ event.nom_image}}" style="width: 200px;height: 100px">

            </tr>
        </tbody>
    </table>

    <a href="{{ path('event_index') }}">back to list</a>

    <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_form.html.twig') }}

<div class="top-campaign">
    <h3 class="title-3 m-b-30">Commentaires : </h3>
        <table>
            <tbody>
            {% for c in comments %}
            <tr>
               <td>
                {{ c.commentaire }} </td>
                <Td>
                <a href="{{ path('commentaire_edit', {'id': c.id}) }}">edit</a>
                </td>
            </tr>

            </tbody>
        </table>
            {% endfor %}
    <br>
    <br>
    <br>
    <br>

    <div class="card my-4">
        <br>


        <div class="card-body">
            <h1>Create new Commentaire</h1>

            {{ include('commentaire/_form.html.twig') }}
        </div>
    </div>
{% endblock %}
    {% block body5 %}
    {% endblock %}

    {% block body6 %}
    {% endblock %}